# Base
FROM containers.chewed-k8s.net/docker_hub_cache/library/node:20-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

## Copy the files
WORKDIR /frontend
COPY package*.json ./
COPY pnpm-lock.yaml ./
COPY public ./public
COPY src ./src
COPY public ./public
COPY tsconfig.json ./
COPY config-overrides.js ./

# Install dependencies
FROM base AS dependencies
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --production

# Build
FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm build

# Runner
FROM build AS runner
RUN pnpm install -g serve
CMD ["serve", "-s", "build", "-l", "80"]
