name: Pull Requests
on:
  push:
    branches-ignore:
      - main
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run test --passWithNoTests
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    needs: test
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
